server:
    port: 9001
    servlet:
        context-path: /ui
        session:
          cookie:
            name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://127.0.0.1:8081/auth/oauth/token
      userAuthorizationUri: http://127.0.0.1:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://127.0.0.1:8081/auth/user/me
